project:
  name: "Git Commit Message Generation"
  version: "0.1"

data:
  raw_data_path: "data/raw_data/"
  processed_data_path: "data/processed_data/"
  train_file: "data/processed_data/train.json"
  test_file: "data/processed_data/test.json"
  validation_split: 0.1

model:
  model_name:
  save_dir:

training:
  batch_size: 16
  epochs: 5
  learning_rate: 5e-5
  max_seq_length: 512

evaluation:
  metrics: ["BLEU", "ROUGE"]
