[project]
authors = ["ndersam <ndersamuel@gmail.com>"]
channels = ["conda-forge"]
description = "This project aims to use machine learning and natural language processing techniques to automatically generate high-quality Git commit messages based on code changes (git diff)."
name = "cmg"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"
readme = "README.md"
repository = "https://github.com/ZHCSJ666/ML-24-25"

[tasks]
format = { cmd="black src tests --line-length 99", cwd= "./"}

[system-requirements]
cuda = "12.4"

[dependencies]
python = "3.11.*"
pytorch = "2.5.1.*"
lightning = "2.*"
torchmetrics = "0.*"
hydra-core = "1.*"
rich = "13.*"
pre-commit = "3.*"
pytest = "7.*"
pandas = ">=2.2.3,<3"
transformers = ">=4.48.0,<5"
datasets = ">=3.2.0,<4"
evaluate = ">=0.4.1,<0.5"
jupyterlab = ">=4.3.4,<5"
wandb = ">=0.19.4,<0.20"
hydra-colorlog = ">=1.2.0,<2"
tqdm = ">=4.67.1,<5"
torchinfo = ">=1.8.0,<2"
matplotlib = ">=3.10.0,<4"
seaborn = ">=0.13.2,<0.14"
nltk = ">=3.9.1,<4"
sentencepiece = ">=0.2.0,<0.3"
tensorboard = ">=2.18.0,<3"
loguru = ">=0.7.2,<0.8"
openai = ">=1.59.8,<2"
tiktoken = ">=0.8.0,<0.9"
tenacity = ">=9.0.0,<10"
polars = ">=1.17.1,<2"
rapidfuzz = ">=3.11.0,<4"
sacrebleu = ">=2.5.1,<3"
black = ">=24.10.0,<25"
bert_score = ">=0.3.9,<0.4"
pixi-pycharm = ">=0.0.8,<0.0.9"
httpx = "==0.27.2"

[pypi-dependencies]
hydra-optuna-sweeper = ">=1.2.0, <2"
rootutils = ">=1.0.7, <2"
rouge-score = ">=0.1.2, <0.2"
cmg = { path = ".", editable = true }
ollama = ">=0.4.6, <0.5"
marisa-trie = ">=1.2.1, <2"

