_target_: src.utils.chat_completion.GPTChatCompleter
model: gpt-4o-mini-2024-07-18
api_key: ${oc.env:OPENAI_API_KEY}
# batch queue limit for gpt-4o-mini https://platform.openai.com/settings/organization/limits
batch_limit_tpd: 2_000_000
temperature: 0.7
max_prompt_token_count: ${..max_prompt_token_count}
max_response_token_count: 300