_target_: src.models.cmg_module.CommitMessageGenerationModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: models.components.seq2seq_wrapper.Seq2SeqWrapper
  model:
    _target_: transformers.models.t5.modeling_t5.T5ForConditionalGeneration
    config:
      # See https://huggingface.co/docs/transformers/en/model_doc/t5#transformers.T5Config
      _target_: transformers.models.t5.configuration_t5.T5Config.from_json_file
      json_file: ${paths.root_dir}/configs/model/flan_t5_small.json
  encoder_context_max_len: ???
  decoder_context_max_len: ???
  encoder_vocab_size: ???
  decoder_vocab_size: ???

# compile model for faster training with pytorch 2.0
compile: false
