defaults:
  - model_checkpoint
#  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}-val_MRR_top5_{val/MRR_top5:.4f}"
  monitor: "val/MRR_top5"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

model_checkpoint_on_text:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}-val_sacre_bleu4_{val/sacre_bleu4:.4f}"
  monitor: "val/sacre_bleu4"
  mode: "max"
  save_last: False
  auto_insert_metric_name: False
  verbose: False

#early_stopping:
#  monitor: "val/loss"
#  patience: 100
#  mode: "min"

model_summary:
  max_depth: -1

learning_rate_monitor:
  _target_: lightning.pytorch.callbacks.lr_monitor.LearningRateMonitor
  logging_interval: step
