# @package _global_

defaults:
  - _self_
  - data: commit-chronicle
  - model: t5-efficient-tiny
  - callbacks: null
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
