# @package _global_
defaults:
  - _self_
  - chat_completer: qwen2.5-coder-7b

_target_: src.simplify_data.MainDictConfig

# Optional: Can be one of train, test, or validation
split:
languages: ["Go"]
change_types: []
diff_line_sep: "\n"

# should be one of 'prompt-testing', 'eager' or 'batch'
mode: prompt-testing
seed: 419
prompt_testing_example_index: 100 # use -1 for random example
# for debugging purposes during eager or batch mode
debug_run: True

system_content: You are a helpful assistant that simplifies commit messages.
user_content_template: |-
  Code changes:
  {diff}
  
  Original message: {message}
  
  Create a simplified commit message following these strict rules:
  1. Maximum 16 words
  2. Use only these verbs: add, update, remove, fix, refactor
  3. Reference only code elements visible in the diff
  4. Format: "<verb> <optional code element> <brief detail>" e.g. Add documentation for unit testing
  5. Exclude all contextual information not visible in the code changes
  6. Focus on the technical change, not the purpose or impact
  7. Use consistent terminology for similar changes
  8. Use only one line or sentence.
  9. Output only the simplified message without any explanation or formatting.
#max_msg_token_count: 64
#max_prompt_token_count: 1000
max_msg_token_count: 24
max_prompt_token_count: 1000


huggingface_repo:

# paths
# ############

# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to cache intermediate shit
output_dir: ${.root_dir}/data/cleaning/

hydra:
  run:
    dir: ${...root_dir}/logs/data_simplification/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
